- name: install unzip package
  apt:
    pkg: unzip
    state: present

- name: unarchive rwc3 file
  unarchive:
    src: "{{ file_path }}/{{ rwc3_archive }}"
    dest: "{{ client_user_home }}"

- name: make install_deb.sh executable
  file:
    path: "{{ client_user_home}}/Intel_RWC3_Linux_007.019.006.000/x64/install_deb.sh"
    mode: 0777
